name: Continuous Integration

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
    - name: Unittests
      run: |
        conda install pytest
        $CONDA/bin/pytest
